site_name: octadocs-decisions
repo_url: https://github.com/octadocs/octadocs-decisions
repo_name: octadocs-decisions
copyright: Copyright &copy; 2021 OctaDocs

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - octadocs
  - octadocs_decisions

theme:
  name: material
#  custom_dir: templates
